# Generated by Django 4.0.10 on 2023-11-27 20:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('grade_of_research', models.IntegerField()),
                ('grade_of_poster', models.IntegerField()),
                ('grade_of_presentation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=45)),
                ('second_name', models.CharField(max_length=45)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('login', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='man.person')),
            ],
        ),
    ]
