# Generated by Django 4.0.10 on 2023-12-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0005_grade_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='person',
        ),
    ]
